services:
  postgres:
    container_name: estudos-postgres
    image: postgres:15-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    expose:
      - 5434
    ports:
      - 5434:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data:


